/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.example.domain.Feed;
import org.example.service.FeedService;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.util.HashMap;
import java.util.List;


public class App {
  private static final Logger logger = LoggerFactory.getLogger(App.class);
  private static final FeedService feedService = new FeedService();

  public static void main(String[] args) {
    var appArguments = new HashMap<String, String>();
    List.of(args).forEach(arg -> {
      var keyValue = arg.split("=");
      appArguments.put(keyValue[0], keyValue[1]);
    });

    var feeds = feedService.getFeeds(appArguments);
    printFeeds(feeds, appArguments.getOrDefault("q", ""));

  }

  private static void printFeeds(List<Feed> feeds, String query) {
    var feedCollector = new StringBuilder(String.format("""
            
            *************************************************************************
            ****************  FEEDS FOR: %s  ********************************************
            ************************************************************************
            
            """, query));

    feeds.forEach(feed -> {
      feedCollector.append(feed.toString());
      feedCollector.append("\n");
    });

    logger.info(feedCollector.toString());
  }

}
